# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alec < Formula
  desc "Terminal UI for organizing and executing scripts without CLI maintenance overhead"
  homepage "https://github.com/shaiu/alec"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shaiu/alec/releases/download/v0.1.0/alec_0.1.0_darwin_x86_64.tar.gz"
    sha256 "c3f50ea9de7ec435e9715adbe7afed318b0a227276a7d0de87ecf07f5b87149d"

    def install
      bin.install "alec"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shaiu/alec/releases/download/v0.1.0/alec_0.1.0_darwin_aarch64.tar.gz"
    sha256 "68742abd50d2c8a79e3671df8ba43949094f79cdb9812b9f33ae25c75acacb32"

    def install
      bin.install "alec"
    end
  end

  test do
    system "#{bin}/alec", "--version"
  end
end
