# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alec < Formula
  desc "Terminal UI for organizing and executing scripts without CLI maintenance overhead"
  homepage "https://github.com/shaiu/alec"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/shaiu/alec/releases/download/v0.1.0/alec_0.1.0_darwin_x86_64.tar.gz"
    sha256 "7b4466a9646cdf468d8d240886052e29f61484b12638fb4bfb30ed986714f04c"

    def install
      bin.install "alec"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/shaiu/alec/releases/download/v0.1.0/alec_0.1.0_darwin_aarch64.tar.gz"
    sha256 "72dfff6508c69f1214d56812a2adfde7b4835bda02b0d5e5c047d4ed4843e64c"

    def install
      bin.install "alec"
    end
  end

  test do
    system "#{bin}/alec", "--version"
  end
end
