# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tap < Formula
  desc "Terminal-based script runner with interactive TUI"
  homepage "https://github.com/shaiungar/tap"
  version "0.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/shaiu/tap/releases/download/v0.2.0/tap_0.2.0_darwin_all.tar.gz"
    sha256 "c7d22035bb05d88638681e7ffa20da0e388cd0bdc280fbfdaea66fd11bd810dd"

    define_method(:install) do
      bin.install "tap"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaiu/tap/releases/download/v0.2.0/tap_0.2.0_linux_amd64.tar.gz"
      sha256 "b5e79efc860322849572b9937da01ff03d021138e9dbbcc6ebd3152d79dfa553"
      define_method(:install) do
        bin.install "tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaiu/tap/releases/download/v0.2.0/tap_0.2.0_linux_arm64.tar.gz"
      sha256 "7224cdc379b9d0ff47ada9a58dd16212e7a3bb9169a9b8d7086a8d867bd855b4"
      define_method(:install) do
        bin.install "tap"
      end
    end
  end

  test do
    system "#{bin}/tap", "version"
  end
end
