# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tap < Formula
  desc "Terminal-based script runner with interactive TUI"
  homepage "https://github.com/shaiungar/tap"
  version "0.3.1"
  license "MIT"

  on_macos do
    url "https://github.com/shaiu/tap/releases/download/v0.3.1/tap_0.3.1_darwin_all.tar.gz"
    sha256 "e76d9b5efa92738472fa4da6bd97275fc0ac855ba11533ff7b5710471ae32b67"

    define_method(:install) do
      bin.install "tap"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaiu/tap/releases/download/v0.3.1/tap_0.3.1_linux_amd64.tar.gz"
      sha256 "8ee4476abf093ce0f811b585fbfc7066332381133057d66473af509fa93de617"
      define_method(:install) do
        bin.install "tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shaiu/tap/releases/download/v0.3.1/tap_0.3.1_linux_arm64.tar.gz"
      sha256 "8147b54d40347d56ccece106f7fe585eb0ec902785d88c6dfc0c4b0b2263a9bd"
      define_method(:install) do
        bin.install "tap"
      end
    end
  end

  test do
    system "#{bin}/tap", "version"
  end
end
